name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  terraform_plan:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Format Terraform
        id: fmt
        run: terraform fmt -check -no-color -recursive
        continue-on-error: true

      - name: Initialize Terraform
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform
        id: validate
        run: terraform validate
        working-directory: ./terraform
        
      - name: Plan Terraform
        id: plan
        run: terraform plan -no-color

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `Terraform Plan: \`${{ steps.plan.outcome }}\`
            <details><summary>Plan Output</summary>

            \`\`\`
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            </details>`           
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
