name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  tf_version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Formatting Terraform
        run: terraform fmt -check -no-color -recursive
        working-directory: .